---
- hosts: vmware
  vars_prompt:
    - name: "vm_name"
      prompt: "vm name"
      private: no
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  gather_facts: false
  connection: local
  user: remote
  become: yes 
  roles:
    - { role: deployvmware }

- hosts: novamaquina
  vars_prompt:
    - name: "newhostname"
      prompt: "Insira o novo hostname"
      private: no

  roles:
    - { role: confbase }
    - { role: tomcat } 
